"""changed primary key to id

Revision ID: 694268de2573
Revises: 904d65f42e0e
Create Date: 2025-03-23 22:29:52.615348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '694268de2573'
down_revision: Union[str, None] = '904d65f42e0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'uuid',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint('users_uuid_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_uuid_key', 'users', ['uuid'])
    op.alter_column('users', 'uuid',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
