"""added email confirmation

Revision ID: c888178d19c1
Revises: eb8773374cde
Create Date: 2025-03-24 16:35:02.723965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c888178d19c1'
down_revision: Union[str, None] = 'eb8773374cde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('confirmation_token', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'users', ['confirmation_token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'confirmation_token')
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###
