"""changed uuid to unique

Revision ID: eb8773374cde
Revises: 694268de2573
Create Date: 2025-03-23 22:34:11.556871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb8773374cde'
down_revision: Union[str, None] = '694268de2573'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'uuid',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_unique_constraint(None, 'users', ['uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'uuid',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
